### ISSUE TITLE
some questions

### ISSUE THREAD

**Issue by szhang963** [jiangxb98/SleepMonitor-Nano#1]
Hi, Could I ask your WeChat? I want to ask you some questions. 
I appreciate it if you could agree.
Best.

**Comment by jiangxb98** [comment]
Please send your WeChat to ***@***.***



---Original---
From: ***@***.***&gt;
Date: Fri, Aug 16, 2024 17:50 PM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [jiangxb98/SleepMonitor-Nano] hi (Issue #1)




 
Could I ask your WeChat? I want to ask you some questions.
 I appreciate it if you could agree.
 Best.

**Comment by jiangxb98** [comment]
> Hi, Could I ask your WeChat? I want to ask you some questions. I appreciate it if you could agree. Best.

Please send your WeChat to the 1587884826 @ qq.com
